from scrapy.cmdline import execute
import os
import sys

# print(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
# execute(["scrapy", "crawl", "1"])
# execute(["scrapy", "crawl", "2"])
# execute(["scrapy", "crawl", "3"])
# execute(["scrapy", "crawl", "4"])
# execute(["scrapy", "crawl", "5"])
# execute(["scrapy", "crawl", "lingshou"])
# execute(["scrapy", "crawl", "zanhuang"])
# execute(["scrapy", "crawl", "pingshan"])
# execute(["scrapy", "crawl", "qinglong"])
# execute(["scrapy", "crawl", "daming"])
# execute(["scrapy", "crawl", "wei"])
# execute(["scrapy", "crawl", "lin"])
# execute(["scrapy", "crawl", "guangzong"])
# execute(["scrapy", "crawl", "pingxiang"])
# execute(["scrapy", "crawl", "weixian"])
# execute(["scrapy", "crawl", "fuping"])
# execute(["scrapy", "crawl", "tangxian"])
# execute(["scrapy", "crawl", "laiyuan"])
# execute(["scrapy", "crawl", "shunping"])
# execute(["scrapy", "crawl", "18"])
# execute(["scrapy", "crawl", "19"])
# execute(["scrapy", "crawl", "20"])
# execute(["scrapy", "crawl", "34"])
# execute(["scrapy", "crawl", "36"])
# execute(["scrapy", "crawl", "37"])
# execute(["scrapy", "crawl", "39"])
# execute(["scrapy", "crawl", "41"])
# execute(["scrapy", "crawl", "47"])
# execute(["scrapy", "crawl", "36"])
# execute(["scrapy", "crawl", "38"])
# execute(["scrapy", "crawl", "49_crawl"])
# execute(["scrapy", "crawl", "50_crawl"])
execute(["scrapy", "crawl", "51_crawl"])
